import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='antialiased bg-gray-50'>
        <Header />
        <main
          className='
            mx-auto
            px-4
            sm:px-6
            xl:px-90
            min-h-svh
            bg-gray-50
          '
        >
          {children}
        </main>
      </body>
    </html>
  );
}
